/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jyms;

import com.sun.jna.NativeLong;
import jyms.ui.SliderUI_White;

/**
 *
 * @author John
 */
public class JDialogVideoEffectSet extends javax.swing.JDialog {

    private String sFileName = this.getClass().getName() + ".java";
    private ChannelRealPlayer channelRealPlayer2;
    private NativeLong m_lRealHandle;//预览句柄
    
    private int m_iBrightness;//亮度
    private int m_iContrast;//对比度
    private int m_iSaturation;//饱和度
    private int m_iHue;//色度

    private int m_iVolume;//音量
    
    private boolean bIntialSelect = true;//是否是初始化赋值时，触发StateChanged事件
    
    
    /**
     * Creates new form JDialogVideoEffectSet
     * @param parent
     * @param modal
     * @param ChannelRealPlayer2
     */
    public JDialogVideoEffectSet(java.awt.Frame parent, boolean modal,ChannelRealPlayer ChannelRealPlayer2) {
        super(parent, modal);
        this.channelRealPlayer2 = ChannelRealPlayer2;
        m_lRealHandle = ChannelRealPlayer2.getPreviewHandle();
        initComponents();
        modifyLocales();
        initialFrameParas();
        bIntialSelect = false;//是否是初始化赋值时，触发StateChanged事件
    }
     
     /**
	 * 函数:      initialFrameParas
         * 函数描述:  初始化窗口参数
    */
    private void initialFrameParas(){
        if (channelRealPlayer2.getVideoEffect("")){
            jSliderBright.setValue(channelRealPlayer2.getBrightness());
            jSliderContrast.setValue(channelRealPlayer2.getContrast());
            jSliderSaturation.setValue(channelRealPlayer2.getSaturation());
            jSliderHue.setValue(channelRealPlayer2.getHue());
        }
        jSliderVolume.setValue(channelRealPlayer2.getVolume());
        //UI设置
        jSliderBright.setUI(new SliderUI_White(jSliderBright));
        jSliderContrast.setUI(new SliderUI_White(jSliderContrast));
        jSliderHue.setUI(new SliderUI_White(jSliderHue));
        jSliderSaturation.setUI(new SliderUI_White(jSliderSaturation));
        jSliderVolume.setUI(new SliderUI_White(jSliderVolume));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVideoPara = new javax.swing.JPanel();
        jLabelContrast = new javax.swing.JLabel();
        jLabelSaturation = new javax.swing.JLabel();
        jLabelHue = new javax.swing.JLabel();
        jLabelVolume = new javax.swing.JLabel();
        jLabelBright = new javax.swing.JLabel();
        jButtonDefault = new javax.swing.JButton();
        jSliderVolume = new javax.swing.JSlider();
        jSliderHue = new javax.swing.JSlider();
        jSliderSaturation = new javax.swing.JSlider();
        jSliderContrast = new javax.swing.JSlider();
        jSliderBright = new javax.swing.JSlider();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("视频参数设置");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelVideoPara.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelContrast.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelContrast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContrast.setText("对比度");

        jLabelSaturation.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelSaturation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSaturation.setText("饱和度");

        jLabelHue.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelHue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHue.setText("色度");

        jLabelVolume.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelVolume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVolume.setText("音量");

        jLabelBright.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelBright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBright.setText("亮度");

        jButtonDefault.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/devpararestore.png"))); // NOI18N
        jButtonDefault.setText("默认值");
        jButtonDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefaultActionPerformed(evt);
            }
        });

        jSliderVolume.setMinimum(1);
        jSliderVolume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVolumeStateChanged(evt);
            }
        });

        jSliderHue.setMaximum(10);
        jSliderHue.setMinimum(1);
        jSliderHue.setValue(6);
        jSliderHue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderHueStateChanged(evt);
            }
        });

        jSliderSaturation.setMaximum(10);
        jSliderSaturation.setMinimum(1);
        jSliderSaturation.setValue(6);
        jSliderSaturation.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSaturationStateChanged(evt);
            }
        });

        jSliderContrast.setMaximum(10);
        jSliderContrast.setMinimum(1);
        jSliderContrast.setValue(6);
        jSliderContrast.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderContrastStateChanged(evt);
            }
        });

        jSliderBright.setForeground(new java.awt.Color(0, 0, 0));
        jSliderBright.setMaximum(10);
        jSliderBright.setMinimum(1);
        jSliderBright.setValue(6);
        jSliderBright.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderBrightStateChanged(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/exit.png"))); // NOI18N
        jButtonExit.setText("退出");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVideoParaLayout = new javax.swing.GroupLayout(jPanelVideoPara);
        jPanelVideoPara.setLayout(jPanelVideoParaLayout);
        jPanelVideoParaLayout.setHorizontalGroup(
            jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVideoParaLayout.createSequentialGroup()
                .addGroup(jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVideoParaLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButtonDefault)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonExit))
                    .addGroup(jPanelVideoParaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelBright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelContrast, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jLabelSaturation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelHue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderBright, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderContrast, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderSaturation, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderHue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanelVideoParaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonDefault, jButtonExit});

        jPanelVideoParaLayout.setVerticalGroup(
            jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVideoParaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderBright, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBright))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContrast)
                    .addComponent(jSliderContrast, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSaturation)
                    .addComponent(jSliderSaturation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHue)
                    .addComponent(jSliderHue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVolume)
                    .addComponent(jSliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanelVideoParaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelVideoPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVideoPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDefaultActionPerformed
        m_iBrightness = 6;
        m_iContrast = 6;
        m_iSaturation = 6;
        m_iHue = 6;
        m_iVolume = 50;

        jSliderBright.setValue(6);
        jSliderContrast.setValue(6);
        jSliderSaturation.setValue(6);
        jSliderHue.setValue(6);
        jSliderVolume.setValue(50);
        
        channelRealPlayer2.setHue(m_iHue, false);
        channelRealPlayer2.setSaturation(m_iSaturation, false);
        channelRealPlayer2.setContrast(m_iContrast, false);
        channelRealPlayer2.setBrightness(m_iBrightness, false);

        channelRealPlayer2.setVideoEffect("");
        channelRealPlayer2.setVolume(m_iVolume);
    }//GEN-LAST:event_jButtonDefaultActionPerformed

    private void jSliderVolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVolumeStateChanged
        if(bIntialSelect) return;//是否是初始化赋值时，触发StateChanged事件
        m_iVolume = jSliderVolume.getValue();

        channelRealPlayer2.setVolume(m_iVolume);
//        if (CommonParas.g_lVoiceHandle.intValue() >= 0)
//        {
//            CommonParas.hCNetSDK.NET_DVR_SetVoiceComClientVolume(CommonParas.g_lVoiceHandle, (short) (m_iVolume * ((0xffff) / 100)));
//            channelRealPlayer2.writePreviewLog(sSetVoiceIntercomVolume);// "设置语音对讲客户端的音量"
//        }
    }//GEN-LAST:event_jSliderVolumeStateChanged

    private void jSliderHueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderHueStateChanged
        if(bIntialSelect) return;//是否是初始化赋值时，触发StateChanged事件
        m_iHue = jSliderHue.getValue();
        channelRealPlayer2.setHue(m_iHue, true);
        //setVideoEffect(sChromaAdjustment);// "色度调节"
    }//GEN-LAST:event_jSliderHueStateChanged

    private void jSliderSaturationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSaturationStateChanged
        if(bIntialSelect) return;//是否是初始化赋值时，触发StateChanged事件
        m_iSaturation = jSliderSaturation.getValue();
        channelRealPlayer2.setSaturation(m_iSaturation, true);
        //setVideoEffect(sSaturationAdjustment);// "饱和度调节"
    }//GEN-LAST:event_jSliderSaturationStateChanged

    private void jSliderContrastStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderContrastStateChanged
        if(bIntialSelect) return;//是否是初始化赋值时，触发StateChanged事件
        m_iContrast = jSliderContrast.getValue();
        channelRealPlayer2.setContrast(m_iContrast, true);
        //setVideoEffect(sContrastAdjustment);// "对比度调节"
    }//GEN-LAST:event_jSliderContrastStateChanged

    private void jSliderBrightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderBrightStateChanged
        if(bIntialSelect) return;//是否是初始化赋值时，触发StateChanged事件
        m_iBrightness = jSliderBright.getValue();
        channelRealPlayer2.setBrightness(m_iBrightness, true);
        //setVideoEffect(sBrightnessAdjustment);// "亮度调节"
    }//GEN-LAST:event_jSliderBrightStateChanged

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        //写日志
        //channelRealPlayer2.writePreviewLog("结束视频参数设置");
        dispose();
        
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        jButtonExit.doClick();
    }//GEN-LAST:event_formWindowClosing

//    private boolean setVideoEffect(String Description)
//    {
//        if(!CommonParas.hCNetSDK.NET_DVR_ClientSetVideoEffect(m_lRealHandle, m_iBrightness, m_iContrast, m_iSaturation, m_iHue))
//        {
//            //JOptionPane.showMessageDialog(this, "设置预览视频显示参数失败");
//            CommonParas.showErrorMessage(sSetVideoDisplayParaFail, channelRealPlayer2.getDeviceparaBean().getAnothername(), sFileName);// "设置预览视频显示参数失败"
//            return false;
//        }else{
//            if (!Description.equals("")) channelRealPlayer2.writePreviewLog(sSetVideoDisplayPara, Description);// "设置预览视频显示参数"
//            return true;
//        }
//    }
    
    /**
        * 函数:      modifyLocales
        * 函数描述:  根据系统语言设置窗口的控件信息和消息文本
    */
    private void modifyLocales(){
        
        if (CommonParas.SysParas.ifChinese) return;//如果是中文，则不做任何操作
        
        MyLocales Locales = CommonParas.SysParas.sysLocales;
        
        //信息显示
        sTitle = Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.sTitle");  //视频参数设置
//        sSetVideoDisplayPara = Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.sSetVideoDisplayPara");  //设置预览视频显示参数
//        sSetVideoDisplayParaFail = Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.sSetVideoDisplayParaFail");  //设置预览视频显示参数失败
//        sSetVoiceIntercomVolume = Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.sSetVoiceIntercomVolume");  //设置语音对讲客户端的音量
//        sChromaAdjustment = Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.sChromaAdjustment");  //色度调节
//        sSaturationAdjustment = Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.sSaturationAdjustment");  //饱和度调节
//        sContrastAdjustment = Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.sContrastAdjustment");  //对比度调节
//        sBrightnessAdjustment = Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.sBrightnessAdjustment");  //亮度调节
        //标签和按钮显示
        jLabelContrast.setText( Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.jLabelContrast"));  //对比度
        jLabelSaturation.setText( Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.jLabelSaturation"));  //饱和度
        jLabelHue.setText( Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.jLabelHue"));  //色度
        jLabelVolume.setText( Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.jLabelVolume"));  //音量
        jLabelBright.setText( Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.jLabelBright"));  //亮度
        jButtonDefault.setText( Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.jButtonDefault"));  //默认值
        jButtonExit.setText( Locales.getString("JFrameTotalPreview", "JDialogVideoEffectSet.jButtonExit"));  //退出

        this.setTitle(sTitle);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDefault;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelBright;
    private javax.swing.JLabel jLabelContrast;
    private javax.swing.JLabel jLabelHue;
    private javax.swing.JLabel jLabelSaturation;
    private javax.swing.JLabel jLabelVolume;
    private javax.swing.JPanel jPanelVideoPara;
    private javax.swing.JSlider jSliderBright;
    private javax.swing.JSlider jSliderContrast;
    private javax.swing.JSlider jSliderHue;
    private javax.swing.JSlider jSliderSaturation;
    private javax.swing.JSlider jSliderVolume;
    // End of variables declaration//GEN-END:variables

    private String sTitle = "视频参数设置";
//    private String sSetVideoDisplayPara = "设置预览视频显示参数";
//    private String sSetVideoDisplayParaFail = "设置预览视频显示参数失败";
//    private String sSetVoiceIntercomVolume = "设置语音对讲客户端的音量";
//    private String sChromaAdjustment = "色度调节";
//    private String sSaturationAdjustment = "饱和度调节";
//    private String sContrastAdjustment = "对比度调节";
//    private String sBrightnessAdjustment = "亮度调节";

}
