/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jyms;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import jyms.data.ClientLogBean;
import jyms.data.CodesBean;
import jyms.data.DeviceParaBean;
import jyms.data.UsersBean;
import jyms.tools.MulitCombobox;

/**
 *
 * @author John
 */
public class JDialogLogFilterSet extends javax.swing.JDialog {

    private final String sFileName = this.getClass().getName() + ".java";
//    private CheckBoxNodeTree.CheckBoxTreeNode m_DeviceRoot;//通道树根节点
    MulitCombobox comboboxDVRType;//设备类型
    MulitCombobox comboboxDVR;//设备
    MulitCombobox comboboxResourceType;//操作对象类型
    MulitCombobox comboboxUserNames;//操作用户
    MulitCombobox comboboxLogType;//日志类型
    
    ArrayList<CodesBean> ListDVRType;//设备类型列表
    ArrayList<String> listDVR;//设备列表
    ArrayList<CodesBean> ListResourceType;//设备资源类型列表
    ArrayList<String> listUserNmes;//操作用户
    ArrayList<CodesBean> ListLogType;//日志类型
    private final int LengthOfCombobox = 500;
    ArrayList<String> listReturn = new ArrayList();
    ArrayList<String> listReturnText = new ArrayList();//过滤条件文字表示
    private int iState = 0;//0表示取消；1表示设置
    /**
     * Creates new form JDialogLogFilterSet
     */
    public JDialogLogFilterSet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modifyLocales();
        intialParas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFirst = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jLabelOperationType = new javax.swing.JLabel();
        jLabelDVRType = new javax.swing.JLabel();
        jPanelDVRType = new javax.swing.JPanel();
        jPanelResourceType = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jPanelUserNmes = new javax.swing.JPanel();
        jLabelLogType = new javax.swing.JLabel();
        jPanelLogType = new javax.swing.JPanel();
        jLabelDVR = new javax.swing.JLabel();
        jPanelDVR = new javax.swing.JPanel();
        jPanelLast = new javax.swing.JPanel();
        jButtonSetup = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("搜索条件设置");
        setUndecorated(true);

        jLabelTitle.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("搜索条件设置");

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/close.png"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFirstLayout = new javax.swing.GroupLayout(jPanelFirst);
        jPanelFirst.setLayout(jPanelFirstLayout);
        jPanelFirstLayout.setHorizontalGroup(
            jPanelFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFirstLayout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFirstLayout.setVerticalGroup(
            jPanelFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFirstLayout.createSequentialGroup()
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelFirst, java.awt.BorderLayout.PAGE_START);

        jLabelOperationType.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelOperationType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOperationType.setText("设备资源类型：");

        jLabelDVRType.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelDVRType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDVRType.setText("设备类型：");
        jLabelDVRType.setToolTipText("");

        jPanelDVRType.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelDVRTypeLayout = new javax.swing.GroupLayout(jPanelDVRType);
        jPanelDVRType.setLayout(jPanelDVRTypeLayout);
        jPanelDVRTypeLayout.setHorizontalGroup(
            jPanelDVRTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDVRTypeLayout.setVerticalGroup(
            jPanelDVRTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanelResourceType.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelResourceTypeLayout = new javax.swing.GroupLayout(jPanelResourceType);
        jPanelResourceType.setLayout(jPanelResourceTypeLayout);
        jPanelResourceTypeLayout.setHorizontalGroup(
            jPanelResourceTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelResourceTypeLayout.setVerticalGroup(
            jPanelResourceTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelUser.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setText("操作用户：");

        jPanelUserNmes.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelUserNmesLayout = new javax.swing.GroupLayout(jPanelUserNmes);
        jPanelUserNmes.setLayout(jPanelUserNmesLayout);
        jPanelUserNmesLayout.setHorizontalGroup(
            jPanelUserNmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanelUserNmesLayout.setVerticalGroup(
            jPanelUserNmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelLogType.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelLogType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogType.setText("日志类型：");

        jPanelLogType.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelLogTypeLayout = new javax.swing.GroupLayout(jPanelLogType);
        jPanelLogType.setLayout(jPanelLogTypeLayout);
        jPanelLogTypeLayout.setHorizontalGroup(
            jPanelLogTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLogTypeLayout.setVerticalGroup(
            jPanelLogTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelDVR.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelDVR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDVR.setText("设  备：");
        jLabelDVR.setToolTipText("");

        jPanelDVR.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelDVRLayout = new javax.swing.GroupLayout(jPanelDVR);
        jPanelDVR.setLayout(jPanelDVRLayout);
        jPanelDVRLayout.setHorizontalGroup(
            jPanelDVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDVRLayout.setVerticalGroup(
            jPanelDVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
            .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCenterLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelLogType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDVRType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDVR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelOperationType, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelUserNmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelLogType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelResourceType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelDVR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelDVRType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
            .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCenterLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelDVRType)
                        .addComponent(jPanelDVRType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelDVR)
                        .addComponent(jPanelDVR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelOperationType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelResourceType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(23, 23, 23)
                    .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelUserNmes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelUser, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGap(24, 24, 24)
                    .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelLogType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelLogType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jButtonSetup.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonSetup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/setup2.png"))); // NOI18N
        jButtonSetup.setText("设 置");
        jButtonSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetupActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/cancel.png"))); // NOI18N
        jButtonCancel.setText("取 消");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLastLayout = new javax.swing.GroupLayout(jPanelLast);
        jPanelLast.setLayout(jPanelLastLayout);
        jPanelLastLayout.setHorizontalGroup(
            jPanelLastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLastLayout.createSequentialGroup()
                .addGap(0, 436, Short.MAX_VALUE)
                .addComponent(jButtonSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addGap(21, 21, 21))
        );

        jPanelLastLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonSetup});

        jPanelLastLayout.setVerticalGroup(
            jPanelLastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSetup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelLast, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetupActionPerformed
        // TODO add your handling code here:
        if (!comboboxUserNames.ifCheckAll()){
            listReturn.add(ClientLogBean.getInLimitOfUserName(comboboxUserNames.getCheckedCodes(), sFileName));//" CLIENTLOG.UserName in ("+ comboboxUserNames.getCheckedCodes() + ")");
            listReturnText.add(comboboxUserNames.getCheckedValues());
        }
        
        if (!comboboxLogType.ifCheckAll()){
            listReturn.add(ClientLogBean.getInLimitOfLogType(comboboxLogType.getCheckedCodes(), sFileName));//" CLIENTLOG.LogType in ("+ comboboxLogType.getCheckedCodes() + ")");
            listReturnText.add(comboboxLogType.getCheckedValues());
        }
        if (!comboboxDVR.ifCheckAll()){
            listReturn.add(ClientLogBean.getInLimitOfSerialNO(comboboxDVR.getCheckedCodes(), sFileName)); //" CLIENTLOG.SERIALNO in ("+comboboxDVR.getCheckedCodes() + ")");
            listReturnText.add(comboboxDVR.getCheckedValues());
        }
        if (!comboboxResourceType.ifCheckAll()){
            listReturn.add(ClientLogBean.getInLimitOfObjectType(comboboxResourceType.getCheckedCodes(), sFileName));//" CLIENTLOG.ObjectType in ("+comboboxResourceType.getCheckedCodes() + ")");
            listReturnText.add(comboboxResourceType.getCheckedValues());
        }
        
        
        iState = 1;//设置
        this.dispose();
    }//GEN-LAST:event_jButtonSetupActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void intialParas(){
        jLabelDVRType.setVisible(false);
        jPanelDVRType.setVisible(false);
//        ListDVRType = CodesBean.getCodesList(CommonParas.DVRType.DVRTYPE,"1",sFileName);
//        String[] DVRTypes = new String[ListDVRType.size()];
//        
//        for (int i=0;i<ListDVRType.size();i++){
//            DVRTypes[i] = ListDVRType.get(i).getCodename();
//        }
//        comboboxDVRType = new MulitCombobox(DVRTypes,DVRTypes,LengthOfCombobox);
//        
//        jPanelDVRType.setLayout(new GridLayout(1, 1));
//        jPanelDVRType.add(comboboxDVRType);
//        jPanelDVRType.updateUI();
//        jPanelDVRType.setBorder(null);
        
        //设备
        ArrayList<String> listDVRs = new ArrayList();
        ArrayList<String> listSerialNOs = new ArrayList();
        
        for (int i=0;i<CommonParas.g_listDeviceDetailPara.size();i++){
            DeviceParaBean deviceParaBean =  CommonParas.getDeviceParaBean(i, sFileName);
            if (deviceParaBean != null) {
                listDVRs.add(deviceParaBean.getAnothername());
                listSerialNOs.add(deviceParaBean.getSerialNO());
            }
        }
        Object[] DVRs = new String[listDVRs.size()];
        Object[] DVRSerialNOs = new String[listSerialNOs.size()];
        
        if (listDVRs.size() > 0) DVRs = listDVRs.toArray(new Object[listDVRs.size()]);
        if (listSerialNOs.size() > 0) DVRSerialNOs = listSerialNOs.toArray(new Object[listSerialNOs.size()]);
        
        comboboxDVR = new MulitCombobox(DVRs, DVRSerialNOs, DVRs, LengthOfCombobox);
        initialComboboxPanel( jPanelDVR , comboboxDVR);

        
        //现在只针对编码设备进行设置
        //ListResourceType = CodesBean.getCodesList(CommonParas.DVRType.DVRTYPE_ENCODINGDVR_CODE,"1",sFileName);
        ListResourceType = CodesBean.getCodesList(CommonParas.DVRResourceType.RESTYPE_ENCODINGDVR_CODE,"1",sFileName);
        String[] DVRResources = new String[ListResourceType.size()];
        String[] DVRResourceCodes = new String[ListResourceType.size()];
        for (int i=0;i<ListResourceType.size();i++){
            DVRResources[i] = ListResourceType.get(i).getCodename();
            DVRResourceCodes[i] = ListResourceType.get(i).getCode();
        }
        comboboxResourceType = new MulitCombobox(DVRResources,DVRResourceCodes,DVRResources,LengthOfCombobox);
        initialComboboxPanel( jPanelResourceType , comboboxResourceType);

        
        //操作用户
        listUserNmes = UsersBean.getUserNameList(sFileName);
        String[] UserNmes = new String[listUserNmes.size()];
        
        for (int i=0;i<listUserNmes.size();i++){
            UserNmes[i] = listUserNmes.get(i);
        }
        comboboxUserNames = new MulitCombobox(UserNmes,UserNmes,UserNmes,LengthOfCombobox);
        initialComboboxPanel( jPanelUserNmes , comboboxUserNames);

        
        //日志类型LogType.LOG_TYPE
        ListLogType = CodesBean.getCodesList(CommonParas.LogType.LOG_TYPE_CODE,"1",sFileName);
        String[] LogTypes = new String[ListLogType.size()];
        String[] LogTypeCodes = new String[ListLogType.size()];
        
        for (int i=0;i<ListLogType.size();i++){
            LogTypes[i] = ListLogType.get(i).getCodename();
            LogTypeCodes[i] = ListLogType.get(i).getCode();
        }
        comboboxLogType = new MulitCombobox(LogTypes,LogTypeCodes,LogTypes,LengthOfCombobox);
        initialComboboxPanel( jPanelLogType , comboboxLogType);

        //设置自定义UI
        CommonParas.setJButtonUnDecorated(jButtonExit);
        //返回列表初始化
//        for (int i=0;i<3;i++){
//            listReturn.add("");
//        }
    }
    private void initialComboboxPanel(JPanel myPanel , MulitCombobox Combox){
        myPanel.setLayout(new GridLayout(1, 1));
        myPanel.add(Combox);
//        myPanel.updateUI();
//        myPanel.setBorder(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogLogFilterSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogLogFilterSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogLogFilterSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogLogFilterSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogLogFilterSet dialog = new JDialogLogFilterSet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
        * 函数:      modifyLocales
        * 函数描述:  根据系统语言设置窗口的控件信息和消息文本
    */
    private void modifyLocales(){
        
        if (CommonParas.SysParas.ifChinese) return;//如果是中文，则不做任何操作

        
        MyLocales Locales = CommonParas.SysParas.sysLocales;
        
        //信息显示
        sTitle = Locales.getString("ClassStrings", "JDialogLogFilterSet.sTitle");  //搜索条件设置
        jLabelOperationType.setText( Locales.getString("ClassStrings", "JDialogLogFilterSet.jLabelOperationType"));  //设备资源类型：
        jLabelDVRType.setText( Locales.getString("ClassStrings", "JDialogLogFilterSet.jLabelDVRType"));  //设备类型：
        jLabelUser.setText( Locales.getString("ClassStrings", "JDialogLogFilterSet.jLabelUser"));  //操作用户：
        jLabelLogType.setText( Locales.getString("ClassStrings", "JDialogLogFilterSet.jLabelLogType"));  //日志类型：
        jLabelDVR.setText( Locales.getString("ClassStrings", "JDialogLogFilterSet.jLabelDVR"));  //设  备：
        jButtonSetup.setText( Locales.getString("ClassStrings", "JDialogLogFilterSet.jButtonSetup"));  //设 置
        jButtonCancel.setText( Locales.getString("ClassStrings", "JDialogLogFilterSet.jButtonCancel"));  //取 消

        //标签和按钮显示
        this.setTitle(sTitle);
        jLabelTitle.setText(sTitle);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSetup;
    private javax.swing.JLabel jLabelDVR;
    private javax.swing.JLabel jLabelDVRType;
    private javax.swing.JLabel jLabelLogType;
    private javax.swing.JLabel jLabelOperationType;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelDVR;
    private javax.swing.JPanel jPanelDVRType;
    private javax.swing.JPanel jPanelFirst;
    private javax.swing.JPanel jPanelLast;
    private javax.swing.JPanel jPanelLogType;
    private javax.swing.JPanel jPanelResourceType;
    private javax.swing.JPanel jPanelUserNmes;
    // End of variables declaration//GEN-END:variables
    
    private String sTitle = "搜索条件设置";

    
    /**
     * @return the listReturn
     */
    public ArrayList<String> getListReturn() {
        return listReturn;
    }

    /**
     * @return the iState
     */
    public int getState() {
        return iState;
    }
    
    /**
     * @return the listReturnText
     */
    public ArrayList<String> getListReturnText() {
        return listReturnText;
    }

}
