/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jyms;

import jyms.tools.endecrypt.MD5Encrypt;
import jyms.data.UsersBean;

/**
 *
 * @author John
 */
public class JDialogModifyPassword extends javax.swing.JDialog {

    private final String sFileName = this.getClass().getName() + ".java";
    /**
     * Creates new form JDialogModifyPassword
     * @param parent
     * @param modal
     */
    public JDialogModifyPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modifyLocales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelNewPassAgain = new javax.swing.JLabel();
        jPasswordFieldNew2 = new javax.swing.JPasswordField();
        jPasswordFieldNew1 = new javax.swing.JPasswordField();
        jLabelNewPass = new javax.swing.JLabel();
        jLabelOldPass = new javax.swing.JLabel();
        jPasswordFieldOld = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("密码修改");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButtonOk.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/ok2.png"))); // NOI18N
        jButtonOk.setText("确  定");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/cancel2.png"))); // NOI18N
        jButtonCancel.setText("取  消");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelNewPassAgain.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNewPassAgain.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelNewPassAgain.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNewPassAgain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewPassAgain.setText("新密码确认：");

        jPasswordFieldNew2.setBackground(new java.awt.Color(64, 64, 64));
        jPasswordFieldNew2.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jPasswordFieldNew2.setForeground(new java.awt.Color(255, 255, 255));

        jPasswordFieldNew1.setBackground(new java.awt.Color(64, 64, 64));
        jPasswordFieldNew1.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jPasswordFieldNew1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNewPass.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNewPass.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelNewPass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNewPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewPass.setText("新密码：");

        jLabelOldPass.setBackground(new java.awt.Color(0, 0, 0));
        jLabelOldPass.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelOldPass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOldPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOldPass.setText("原密码：");

        jPasswordFieldOld.setBackground(new java.awt.Color(64, 64, 64));
        jPasswordFieldOld.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jPasswordFieldOld.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelOldPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNewPassAgain, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordFieldOld)
                    .addComponent(jPasswordFieldNew1)
                    .addComponent(jPasswordFieldNew2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButtonOk)
                .addGap(52, 52, 52)
                .addComponent(jButtonCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldNew1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewPassAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldNew2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        String Password1 = new String(jPasswordFieldNew1.getPassword());
        String Password2 = new String(jPasswordFieldNew2.getPassword());

        String PasswordOld = new String(jPasswordFieldOld.getPassword());

        if (Password1.equals("") && Password2.equals("")) return;

        if (!Password1.equals(Password2)){
            CommonParas.showMessage(sPassNotSame, sFileName);// "两次输入的密码不一致！"
            return;
        }

        int ifModifySuss = UsersBean.modifyPassword(CommonParas.UserState.UserName, MD5Encrypt.getMD5Str(PasswordOld), MD5Encrypt.getMD5Str(Password1),
                                                 CommonParas.getPasswordGrade(CommonParas.UserState.UserName, Password1), sFileName);
        switch (ifModifySuss) {
            case 1:
                CommonParas.SystemWriteLog("",CommonParas.LogType.LOG_OPER_CODE, sModifyPassword , sModifyPasswordSucc, sFileName);//"修改密码" "成功修改密码"
                CommonParas.showMessage(sModifyPasswordSucc, sFileName);// "成功修改密码"
                dispose();
                break;
            case 0://SystemWriteErrorLog(String OperationTime, String Description, String Remarks, String FileName)
                CommonParas.SystemWriteErrorLog("",sModifyPasswordFail, "", sFileName);// "修改密码失败"
                CommonParas.showMessage(sModifyPasswordFail, sFileName);// "修改密码失败"
                break;
            case -1:
                CommonParas.SystemWriteErrorLog("",sModifyPasswordFail, sModifyPasswordError, sFileName);// "修改密码失败" "修改密码过程中出现错误！"
                CommonParas.showMessage(sModifyPasswordError, sFileName);//"修改密码过程中出现错误！"
                break;
            case -2:
                CommonParas.SystemWriteErrorLog("",sModifyPasswordFail, sOriginalPassError, sFileName);// "修改密码失败" "用户原密码输入错误！"
                CommonParas.showMessage(sOriginalPassError, sFileName);//"用户原密码输入错误！"
                break;
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogModifyPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogModifyPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogModifyPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogModifyPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogModifyPassword dialog = new JDialogModifyPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
        * 函数:      modifyLocales
        * 函数描述:  根据系统语言设置窗口的控件信息和消息文本
    */
    private void modifyLocales(){
        
        if (CommonParas.SysParas.ifChinese) return;//如果是中文，则不做任何操作

        
        MyLocales Locales = CommonParas.SysParas.sysLocales;
        
        //信息显示
        sModifyPassword     = Locales.getString("ClassStrings", "JDialogModifyPassword.sModifyPassword");  //密码修改
        sPassNotSame        = Locales.getString("ClassStrings", "JDialogModifyPassword.sPassNotSame");  //两次输入的密码不一致！
        sModifyPasswordSucc = Locales.getString("ClassStrings", "JDialogModifyPassword.sModifyPasswordSucc");  //成功修改密码
        sModifyPasswordFail = Locales.getString("ClassStrings", "JDialogModifyPassword.sModifyPasswordFail");  //修改密码失败
        sModifyPasswordError= Locales.getString("ClassStrings", "JDialogModifyPassword.sModifyPasswordError");  //修改密码过程中出现错误！
        sOriginalPassError  = Locales.getString("ClassStrings", "JDialogModifyPassword.sOriginalPassError");  //用户原密码输入错误！

        //标签和按钮显示
        this.setTitle(sModifyPassword);
        jButtonOk.setText( Locales.getString("ClassStrings", "JDialogModifyPassword.jButtonOk"));  //确  定
        jButtonCancel.setText( Locales.getString("ClassStrings", "JDialogModifyPassword.jButtonCancel"));  //取  消
        jLabelOldPass.setText( Locales.getString("ClassStrings", "JDialogModifyPassword.jLabelOldPass"));  //原密码：
        jLabelNewPass.setText( Locales.getString("ClassStrings", "JDialogModifyPassword.jLabelNewPass"));  //新密码：
        jLabelNewPassAgain.setText( Locales.getString("ClassStrings", "JDialogModifyPassword.jLabelNewPassAgain"));  //新密码确认：
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelNewPass;
    private javax.swing.JLabel jLabelNewPassAgain;
    private javax.swing.JLabel jLabelOldPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldNew1;
    private javax.swing.JPasswordField jPasswordFieldNew2;
    private javax.swing.JPasswordField jPasswordFieldOld;
    // End of variables declaration//GEN-END:variables

    private String sModifyPassword = "密码修改";
    private String sPassNotSame = "两次输入的密码不一致！";
    private String sModifyPasswordSucc = "成功修改密码";
    private String sModifyPasswordFail = "修改密码失败";
    private String sModifyPasswordError = "修改密码过程中出现错误！";
    private String sOriginalPassError = "用户原密码输入错误！";
}
