
package jyms;

import com.sun.jna.NativeLong;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.TableColumnModel;
import jyms.data.DeviceParaBean;
import jyms.data.TxtLogger;
import jyms.tools.TableUtil.JTableCheckBoxModel;
import jyms.ui.PanelUI_MatteBorder;
import jyms.ui.ScrollPaneUI_White;
import jyms.ui.TableHeaderUI_White;
import jyms.ui.TableUI_White;

/**
 *
 * @author John
 */
public class JDialogSetupAlarmCtrl extends javax.swing.JDialog {

    private final String sFileName = this.getClass().getName() + ".java";

    JTableCheckBoxModel  setupAlarmTableModel;
    /**
     * Creates new form JDialogSetupAlarmCtrl
     */
    public JDialogSetupAlarmCtrl(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modifyLocales();
        setupAlarmTableModel = this.initialAlarmOutTableModel();
        
        jTableSetupAlarm.setModel(setupAlarmTableModel);
        jTableSetupAlarm.setRowHeight(30);
        setTableColWidth();
        fillIntoTableSetupAlarm();
        //UI设计
        jPanelContainer.setUI(new PanelUI_MatteBorder());
        jScrollPaneSetupAlarm.setUI(new ScrollPaneUI_White());
        jTableSetupAlarm.setUI(new TableUI_White());
        jTableSetupAlarm.getTableHeader().setUI(new TableHeaderUI_White());
//        jPanelDeviceTypeContainer.setUI(new PanelUI_LineBorder());
        CommonParas.setJButtonUnDecorated(jButtonExit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFirst = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jPanelContainer = new javax.swing.JPanel();
        jScrollPaneSetupAlarm = new javax.swing.JScrollPane();
        jTableSetupAlarm = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("设备报警布防");
        setUndecorated(true);

        jLabelTitle.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("设备报警布防");

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/close.png"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFirstLayout = new javax.swing.GroupLayout(jPanelFirst);
        jPanelFirst.setLayout(jPanelFirstLayout);
        jPanelFirstLayout.setHorizontalGroup(
            jPanelFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFirstLayout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFirstLayout.setVerticalGroup(
            jPanelFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFirstLayout.createSequentialGroup()
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelFirst, java.awt.BorderLayout.PAGE_START);

        jPanelContainer.setLayout(new java.awt.BorderLayout());

        jTableSetupAlarm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSetupAlarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSetupAlarmMouseClicked(evt);
            }
        });
        jScrollPaneSetupAlarm.setViewportView(jTableSetupAlarm);
        jTableSetupAlarm.getAccessibleContext().setAccessibleName("");

        jPanelContainer.add(jScrollPaneSetupAlarm, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTableSetupAlarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSetupAlarmMouseClicked
        // TODO add your handling code here:
        int Row = jTableSetupAlarm.getSelectedRow();
        if (Row < 0 ) return;
        try{
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            
            if (jTableSetupAlarm.getSelectedColumn() == 0){
                modifySetupAlarmParas(Row, true);
            }else{
                //双击
                if (evt.getClickCount() == 2) {
                    modifySetupAlarmParas(Row, false);
                }
            }
        }catch(Exception e){
            TxtLogger.append(this.sFileName, "jTableSetupAlarmMouseClicked()","系统在设置设备报警布防/撤防过程中，出现错误" + 
                            "\r\n                       Exception:" + e.toString());   
        }
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jTableSetupAlarmMouseClicked
    
    
    /**
        * 函数:      modifyAlarmOutParas
        * 函数描述:  修改报警输出的状态
        * @param Row      在JTableModel中的行号
        * @param DirectModify   是否直接点击CheckBox进行修改。false是双击其他栏进行修改
    */
    private void modifySetupAlarmParas(int Row, boolean DirectModify){
        //clicked事件中，单击首列（CheckBox），其返回值则是鼠标点击后的值；双击其他列，则CheckBox显示的还是原来的值，没有改变。
        boolean CurrentIfAlarmOut = (Boolean)setupAlarmTableModel.getValueAt(Row,0);
        
        boolean NewIfAlarmOut = !CurrentIfAlarmOut;//双击事件，则新的值应该和原来的值相反
        if (DirectModify) NewIfAlarmOut = CurrentIfAlarmOut;//点击CheckBox，则新的值就是现在的值。
        
        String OperName = NewIfAlarmOut?sAlarmArming:sAlarmDisarm;//"设备报警布防":"设备报警撤防";
        String OperNameFail = NewIfAlarmOut?sAlarmArmingFail:sAlarmDisarmFail;//"设备报警布防失败":"设备报警撤防失败";

        String AnotherName = (String)setupAlarmTableModel.getValueAt(Row, 1);
        String SerialNo = (String)setupAlarmTableModel.getValueAt(Row, 2);
        //修改数据库中的数据
        boolean bReturn = DeviceParaBean.setupDVRAlarm(SerialNo, NewIfAlarmOut,sFileName);
        if (!bReturn) setupAlarmTableModel.setValueAt(!NewIfAlarmOut, Row, 0);
        else {
            //设置布防/撤销布防
            //setupOneDevAlarmChan函数本身不写日志的，因为有时系统自己会做设置布防/撤防的
            if (CommonParas.setupOneDevAlarmChan(AnotherName, NewIfAlarmOut) < 1) {
                setupAlarmTableModel.setValueAt(!NewIfAlarmOut, Row, 0);
                CommonParas.SystemWriteErrorLog("", AnotherName,  OperNameFail,  SerialNo,  CommonParas.DVRType.DVRTYPE_ENCODINGDVR_CODE,  sFileName);
            }else{
                setupAlarmTableModel.setValueAt(NewIfAlarmOut, Row, 0);
                //操作时间、日志类型、描述信息、设备序列号、设备类型、调用的文件名
                CommonParas.SystemWriteLog("",CommonParas.LogType.LOG_OPER_CODE, OperName, SerialNo, CommonParas.DVRType.DVRTYPE_ENCODINGDVR_CODE, sFileName);
            }
            setupAlarmTableModel.fireTableDataChanged();

        }
    }
    
    /**
        *函数:      fillIntoTableSetupAlarm
        *函数描述:  刷新布防设备列表
    */
    private void fillIntoTableSetupAlarm(){
        try {

            Vector v = setupAlarmTableModel.getDataVector();
            if (v != null) v.clear();
            
            //listDeviceDetailPara获取设备参数表中的 DeviceParaBean-0,设备类型-1（代码表中的代码名称）等参数；
            //现在加上登录ID-2，再加上NET_DVR_Login_V30()设备参数结构体NET_DVR_DEVICEINFO_V30-3;报警布防句柄AlarmHandle-4;
            //IP设备资源及IP通道资源配置结构体NET_DVR_IPPARACFG-5
            for (int i=0;i<CommonParas.g_listDeviceDetailPara.size();i++){
                ArrayList NewList = (ArrayList)CommonParas.g_listDeviceDetailPara.get(i);//
                
                DeviceParaBean deviceParaBean = (DeviceParaBean)NewList.get(0);//
                
                Vector newRow = new Vector();
                NativeLong AlarmHandle = (NativeLong)NewList.get(4);
                if (deviceParaBean.getIfsetupAlarm().equals("1") && AlarmHandle.intValue() > -1)//如果数据库设置了已布防，并且报警布防成功的话（报警布防句柄》-1），设为true
                    newRow.add(true);
                else 
                    newRow.add(false);
                //newRow.add(deviceParaBean.getIfsetupAlarm().equals("1"));
                newRow.add(deviceParaBean.getAnothername());
                newRow.add(deviceParaBean.getSerialNO());
 
                setupAlarmTableModel.addRow(newRow);//和下面的语句效果实际证明是同样的。
//                deviceManagedTableModel.getDataVector().add(newRow);
             }
            setupAlarmTableModel.fireTableDataChanged();
            jTableSetupAlarm.repaint();

        }catch(Exception e)
        {
            TxtLogger.append(this.sFileName, "fillIntoTableSetupAlarm()","系统在刷新布防设备列表过程中，出现错误" + 
                            "\r\n                       Exception:" + e.toString());   
        }
    }
    /**
	 * 函数:      initialAlarmOutTableModel
         * 函数描述:  初始化设备报警输出列表jTableAlarmOut
         * @return JTableButtonModel
    */
    private JTableCheckBoxModel initialAlarmOutTableModel()
    {
        JTableCheckBoxModel  TableModel =new JTableCheckBoxModel(sTableTitle);
        return TableModel;
    }
    /**
	 * 函数:      setTableColWidth
         * 函数描述:  设置表格特殊列的宽度
    */
    private void setTableColWidth(){
        
        TableColumnModel tcmAlarmOut = jTableSetupAlarm.getColumnModel();
        tcmAlarmOut.getColumn(0).setMinWidth(100);
        tcmAlarmOut.getColumn(0).setMaxWidth(120);
        tcmAlarmOut.getColumn(0).setPreferredWidth(100);
        
        tcmAlarmOut.getColumn(1).setMinWidth(120);
        //tcmAlarmOut.getColumn(1).setMaxWidth(480);
        tcmAlarmOut.getColumn(1).setWidth(120);
        
        tcmAlarmOut.getColumn(2).setMinWidth(0);
        tcmAlarmOut.getColumn(2).setMaxWidth(0);
        tcmAlarmOut.getColumn(2).setPreferredWidth(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogSetupAlarmCtrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogSetupAlarmCtrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogSetupAlarmCtrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogSetupAlarmCtrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogSetupAlarmCtrl dialog = new JDialogSetupAlarmCtrl(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
        * 函数:      modifyLocales
        * 函数描述:  根据系统语言设置窗口的控件信息和消息文本
    */
    private void modifyLocales(){
        
        if (CommonParas.SysParas.ifChinese) return;//如果是中文，则不做任何操作
        
        MyLocales Locales = CommonParas.SysParas.sysLocales;
        
        //信息显示
        sTableTitle[0] = Locales.getString("ClassStrings", "JDialogSetupAlarmCtrl.sTableTitle0");  //设置布防
        sTableTitle[1] = Locales.getString("ClassStrings", "JDialogSetupAlarmCtrl.sTableTitle1");  //设备名
        sTableTitle[2] = Locales.getString("ClassStrings", "JDialogSetupAlarmCtrl.sTableTitle2");  //序列号
        sAlarmArming = Locales.getString("ClassStrings", "JDialogSetupAlarmCtrl.sAlarmArming");  //"设备报警布防";
        sAlarmDisarm = Locales.getString("ClassStrings", "JDialogSetupAlarmCtrl.sAlarmDisarm");  //"设备报警撤防";
        sAlarmArmingFail = Locales.getString("ClassStrings", "JDialogSetupAlarmCtrl.sAlarmArmingFail");  //"设备报警布防失败";
        sAlarmDisarmFail = Locales.getString("ClassStrings", "JDialogSetupAlarmCtrl.sAlarmDisarmFail");  //"设备报警撤防失败";
    
        //标签和按钮显示
        this.setTitle(sAlarmArming);
        jLabelTitle.setText(sAlarmArming);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelFirst;
    private javax.swing.JScrollPane jScrollPaneSetupAlarm;
    private javax.swing.JTable jTableSetupAlarm;
    // End of variables declaration//GEN-END:variables

    private String[] sTableTitle = new String[] {"设置布防","设备名","序列号"};
    private String sAlarmArming= "设备报警布防";
    private String sAlarmDisarm= "设备报警撤防";
    
    private String sAlarmArmingFail= "设备报警布防失败";
    private String sAlarmDisarmFail= "设备报警撤防失败";

}
