/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jyms;

import com.sun.jna.NativeLong;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import javax.swing.border.TitledBorder;
import jyms.data.TxtLogger;
import jyms.tools.DateUtil;


/**
 *
 * @author John
 */
public class JDialogPopUpAlarmMSG extends javax.swing.JDialog {
    
    private final String sFileName = this.getClass().getName() + ".java";
    private int iRowOfAAlarmMSG = 0;
    private ChannelRealPlayer channelRealPlayer;//通道预览信息类
    private ChannelPlayBack channelPlayBack;//通道录像回放类
    /**
     * Creates new form JDialogPopUp
     * @param parent
     * @param modal
     * @param RowOfAAlarmMSG
     */
    public JDialogPopUpAlarmMSG(java.awt.Frame parent,boolean modal,int RowOfAAlarmMSG) {

        initComponents();
        modifyLocales();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jyms/image/alarm2.png")));
        this.iRowOfAAlarmMSG = RowOfAAlarmMSG;
        channelRealPlayer = new ChannelRealPlayer();
        channelPlayBack = new ChannelPlayBack();
        getAlarmMSG(RowOfAAlarmMSG);
        
        CommonParas.AlarmRecCtrl.isPopUpAlarmMSGOpened = true;//JDialogPopUpAlarmMSG窗口已经打开
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlarmPlayback = new javax.swing.JPanel();
        panelPlayBack = new java.awt.Panel();
        jButtonNext = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jPanelAlarmInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelAlarmTime2 = new javax.swing.JLabel();
        jLabelAlarmTime = new javax.swing.JLabel();
        jLabelAlarmType2 = new javax.swing.JLabel();
        jLabelAlarmType = new javax.swing.JLabel();
        jLabelDevName2 = new javax.swing.JLabel();
        jLabelDevName = new javax.swing.JLabel();
        jLabelIP2 = new javax.swing.JLabel();
        jLabelIP = new javax.swing.JLabel();
        jLabelChannel2 = new javax.swing.JLabel();
        jLabelChannel = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jPanelRealTimePreview = new javax.swing.JPanel();
        panelPlay = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("报警信息");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelAlarmPlayback.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "报警回放", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 16))); // NOI18N

        panelPlayBack.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelPlayBackLayout = new javax.swing.GroupLayout(panelPlayBack);
        panelPlayBack.setLayout(panelPlayBackLayout);
        panelPlayBackLayout.setHorizontalGroup(
            panelPlayBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        panelPlayBackLayout.setVerticalGroup(
            panelPlayBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelAlarmPlaybackLayout = new javax.swing.GroupLayout(jPanelAlarmPlayback);
        jPanelAlarmPlayback.setLayout(jPanelAlarmPlaybackLayout);
        jPanelAlarmPlaybackLayout.setHorizontalGroup(
            jPanelAlarmPlaybackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlayBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAlarmPlaybackLayout.setVerticalGroup(
            jPanelAlarmPlaybackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlayBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonNext.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/pagelast.png"))); // NOI18N
        jButtonNext.setText("下一条");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonPrevious.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/pagefirst.png"))); // NOI18N
        jButtonPrevious.setText("上一条");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jPanelAlarmInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "报警信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 16))); // NOI18N

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("I D：");

        jLabelID.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelAlarmTime2.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelAlarmTime2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAlarmTime2.setText("时  间：");

        jLabelAlarmTime.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelAlarmTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelAlarmType2.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelAlarmType2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAlarmType2.setText("报警类型：");

        jLabelAlarmType.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelAlarmType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelDevName2.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelDevName2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDevName2.setText("报警设备：");

        jLabelDevName.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelDevName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelIP2.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelIP2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIP2.setText("IP地址：");

        jLabelIP.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelIP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabelChannel2.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelChannel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelChannel2.setText("通道号：");

        jLabelChannel.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelChannel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanelAlarmInfoLayout = new javax.swing.GroupLayout(jPanelAlarmInfo);
        jPanelAlarmInfo.setLayout(jPanelAlarmInfoLayout);
        jPanelAlarmInfoLayout.setHorizontalGroup(
            jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlarmInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAlarmTime2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAlarmType2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlarmType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addComponent(jLabelAlarmTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(48, 48, 48)
                .addGroup(jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDevName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelChannel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelChannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDevName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAlarmInfoLayout.setVerticalGroup(
            jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlarmInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAlarmInfoLayout.createSequentialGroup()
                        .addComponent(jLabelDevName2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIP2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelChannel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAlarmInfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDevName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAlarmTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAlarmTime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAlarmInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAlarmType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAlarmType2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelChannel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanelAlarmInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabelAlarmTime, jLabelAlarmTime2, jLabelAlarmType, jLabelAlarmType2, jLabelChannel, jLabelChannel2, jLabelDevName, jLabelDevName2, jLabelID, jLabelIP, jLabelIP2});

        jButtonExit.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/exit.png"))); // NOI18N
        jButtonExit.setText("退出");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jPanelRealTimePreview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "即时预览", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 16))); // NOI18N

        panelPlay.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelPlayLayout = new javax.swing.GroupLayout(panelPlay);
        panelPlay.setLayout(panelPlayLayout);
        panelPlayLayout.setHorizontalGroup(
            panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        panelPlayLayout.setVerticalGroup(
            panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelRealTimePreviewLayout = new javax.swing.GroupLayout(jPanelRealTimePreview);
        jPanelRealTimePreview.setLayout(jPanelRealTimePreviewLayout);
        jPanelRealTimePreviewLayout.setHorizontalGroup(
            jPanelRealTimePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRealTimePreviewLayout.createSequentialGroup()
                .addComponent(panelPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRealTimePreviewLayout.setVerticalGroup(
            jPanelRealTimePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButtonPrevious)
                .addGap(29, 29, 29)
                .addComponent(jButtonNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAlarmInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelRealTimePreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelAlarmPlayback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(jPanelAlarmInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelRealTimePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAlarmPlayback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNext)
                        .addComponent(jButtonPrevious))
                    .addComponent(jButtonExit))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
        if (iRowOfAAlarmMSG >= CommonParas.alarmMSGTableModel.getRowCount()-1) return;
        iRowOfAAlarmMSG ++;
        getAlarmMSG(iRowOfAAlarmMSG);
//        if (!jButtonPrevious.isEnabled()) jButtonPrevious.setEnabled(true);
//        if (iRowOfAAlarmMSG >= CommonParas.alarmMSGTableModel.getRowCount()-1) jButtonNext.setEnabled(false);
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        if (iRowOfAAlarmMSG <= 0) return;
        iRowOfAAlarmMSG --;
        getAlarmMSG(iRowOfAAlarmMSG);
//        if (!jButtonNext.isEnabled()) jButtonNext.setEnabled(true);
//        if (iRowOfAAlarmMSG  <= 0) jButtonPrevious.setEnabled(false);
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        //不触发formWindowClosing事件，所以必须加上doBeforeCloseAction()函数处理
        doBeforeCloseAction();
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        CommonParas.AlarmRecCtrl.isPopUpAlarmMSGOpened = false;//JDialogPopUpAlarmMSG窗口已经关闭
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //只有右上角关闭按钮才会触发formWindowClosing事件（jButtonExit按钮不会触发formWindowClosing事件，所以必须加上doBeforeCloseAction()函数处理）
        doBeforeCloseAction();
    }//GEN-LAST:event_formWindowClosing
    
    /**
	 * 函数:      doBeforeCloseAction
         * 函数描述:  获得该条报警信息的内容，并显示出来
	 * @param Row	  报警记录号
     */
    private void doBeforeCloseAction(){
        CommonParas.stopPreviewOneChannel(channelRealPlayer, sFileName);
        channelPlayBack.stopPlayBackOnePanel();
    }
    /**
	 * 函数:      getAlarmMSG
         * 函数描述:  获得该条报警信息的内容，并显示出来
	 * @param Row	  报警记录号
     */
    public void getAlarmMSG(int Row){
        //"报警时间",  "报警类型", "IP地址","设备名称", "通道号"
        //alarmMSGTableModel://"ID0", "报警时间1",  "报警类型2", "报警设备3", "通道/报警输入/硬盘号4","接入设备5","通道号6","报警时间2-7","备注8"
        try{
            if (Row < 0 || Row > CommonParas.alarmMSGTableModel.getRowCount() -1) return;
            
            String AnotherName = ((String)CommonParas.alarmMSGTableModel.getValueAt(Row, 3)).trim();
            //String DevIPJoin = ((String)CommonParas.alarmMSGTableModel.getValueAt(Row, 5)).trim();
            String AnotherNameJoin = ((String)CommonParas.alarmMSGTableModel.getValueAt(Row, 5)).trim();
            //String DevIPJoin = CommonParas.getDeviceParaBean(AnotherNameJoin, sFileName).getDVRIP();
            String Channel = ((String)CommonParas.alarmMSGTableModel.getValueAt(Row, 4)).trim();
            String DevIP = CommonParas.getDeviceParaBean(AnotherName, sFileName).getDVRIP();
            String sDate = (String)CommonParas.alarmMSGTableModel.getValueAt(Row, 7);
            
            jLabelID.setText(((String)CommonParas.alarmMSGTableModel.getValueAt(Row, 0)).trim());
            jLabelDevName.setText(AnotherName);
            jLabelIP.setText(DevIP);
            jLabelChannel.setText(Channel);
            jLabelAlarmTime.setText(sDate);
            jLabelAlarmType.setText((String)CommonParas.alarmMSGTableModel.getValueAt(Row, 2));
            
            //设备当前预览
            if (channelRealPlayer.getPreviewHandle().intValue() > -1) 
                CommonParas.stopPreviewOneChannel(channelRealPlayer, sFileName);
            
            CommonParas.setBasicParasOfChannelRealPlayer(channelRealPlayer,DevIP,AnotherName,sFileName);
            channelRealPlayer.setPanelRealplay(panelPlay);
            if (!AnotherNameJoin.equals("")) 
                channelRealPlayer.setChannel(new NativeLong(Integer.parseInt(Channel)+ HCNetSDK.MAX_ANALOG_CHANNUM));
            else 
                channelRealPlayer.setChannel(new NativeLong(Integer.parseInt(Channel)));
            CommonParas.previewOneChannel(channelRealPlayer, sFileName);
            
            //设备报警回放
            if (channelPlayBack.getPlayBackHandle().intValue() > -1)
                channelPlayBack.stopPlayBackOnePanel();
            channelPlayBack.setIndexOflistDevice(CommonParas.getIndexOfDeviceList(AnotherName, sFileName));
            Date dd = DateUtil.convertTimeStringToDate(sDate);
            //提前报警时间10秒回放录像
            channelPlayBack.setStruStartTime(DateUtil.getDateFromNow(dd,Calendar.SECOND,-10));
            channelPlayBack.setStruStopTime(DateUtil.getDateFromNow(dd,Calendar.SECOND,30));
            channelPlayBack.setPanelPlayBack(panelPlayBack);
            if (!AnotherNameJoin.equals("")) 
                channelPlayBack.setChannelNO(new NativeLong(Integer.parseInt(Channel)+ HCNetSDK.MAX_ANALOG_CHANNUM));
            else 
                channelPlayBack.setChannelNO(new NativeLong(Integer.parseInt(Channel)));
            //channelPlayBack.setChannelNO(new NativeLong(Integer.parseInt(Channel)));
            
            channelPlayBack.playBackByTime();
            
            
            setButtonEnable();
        }catch(Exception e)
        {
            TxtLogger.append(this.sFileName, "getAlarmMSG()","系统在获得报警信息并显示的过程中，出现错误" + 
                            "\r\n                       Exception:" + e.toString());   
        }
    }
    /**
	 * 函数:      setButtonEnable
         * 函数描述:  设置按钮的enable属性
     */
    private void setButtonEnable(){
        if (iRowOfAAlarmMSG  <= 0) jButtonNext.setEnabled(false);
        else jButtonNext.setEnabled(true);
        
        if (iRowOfAAlarmMSG >= CommonParas.alarmMSGTableModel.getRowCount()-1) jButtonPrevious.setEnabled(false);
        else jButtonPrevious.setEnabled(true);
        
        if (iRowOfAAlarmMSG == 0 && CommonParas.alarmMSGTableModel.getRowCount() == 1) {
            jButtonPrevious.setEnabled(false);
            jButtonNext.setEnabled(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAlarmTime;
    private javax.swing.JLabel jLabelAlarmTime2;
    private javax.swing.JLabel jLabelAlarmType;
    private javax.swing.JLabel jLabelAlarmType2;
    private javax.swing.JLabel jLabelChannel;
    private javax.swing.JLabel jLabelChannel2;
    private javax.swing.JLabel jLabelDevName;
    private javax.swing.JLabel jLabelDevName2;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIP;
    private javax.swing.JLabel jLabelIP2;
    private javax.swing.JPanel jPanelAlarmInfo;
    private javax.swing.JPanel jPanelAlarmPlayback;
    private javax.swing.JPanel jPanelRealTimePreview;
    private java.awt.Panel panelPlay;
    private java.awt.Panel panelPlayBack;
    // End of variables declaration//GEN-END:variables

    /**
        * 函数:      modifyLocales
        * 函数描述:  根据系统语言设置窗口的控件信息和消息文本
    */
    private void modifyLocales(){
        
        if (CommonParas.SysParas.ifChinese) return;//如果是中文，则不做任何操作
        
        MyLocales Locales = CommonParas.SysParas.sysLocales;
        

        //标签和按钮显示
        this.setTitle(Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.sTitle"));//报警信息

        ((TitledBorder)jPanelRealTimePreview.getBorder()).setTitle( Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jPanelRealTimePreview"));//即时预览
        ((TitledBorder)jPanelAlarmPlayback.getBorder()).setTitle(   Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jPanelAlarmPlayback"));//报警回放
        ((TitledBorder)jPanelAlarmInfo.getBorder()).setTitle(       Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jPanelAlarmInfo"));//报警信息
        
        jButtonNext.setText(        Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jButtonNext"));//下一条
        jButtonPrevious.setText(    Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jButtonPrevious"));//上一条
        jLabelAlarmTime2.setText(   Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jLabelAlarmTime2"));//时  间：
        jLabelAlarmType2.setText(   Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jLabelAlarmType2"));//报警类型：
        jLabelDevName2.setText(     Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jLabelDevName2"));//报警设备：
        jLabelIP2.setText(          Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jLabelIP2"));//IP地址：
        jLabelChannel2.setText(     Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jLabelChannel2"));//通道号：
        jButtonExit.setText(        Locales.getString("ClassStrings", "JDialogPopUpAlarmMSG.jButtonExit"));//退出

    }


}
