/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jyms;

/**
 *
 * @author John
 */
public class JFrameSplash3 extends javax.swing.JFrame {

    private final int iLabelProcessDescHeight;//jLabelProcessDesc
    private final int iFrameHeight;
    private final int iFrameWidth;
    private static JFrameSplash3 instance = null;
    /**
     * Creates new form JFrameSplash
     */
    public JFrameSplash3() {
        initComponents();
        iLabelProcessDescHeight = jLabelProcessDesc.getHeight(); 
        iFrameHeight = this.getHeight();
        iFrameWidth = this.getWidth();
    }
    
    public static void showSplashWindow() {
        if(instance==null){
            instance = new JFrameSplash3();
            CommonParas.centerWindow(instance);
            instance.setLabelProcessDesc("");
            instance.setVisible(true);
        }else if (!instance.isVisible()){
            instance.setVisible(true);
        }
    }
    public static void closeSplashWindow(){
        if (instance.isVisible()) 
            instance.dispose();
    }
    
    public static void setProcessDesc(String ProcessDesc){
        //showSplashWindow();
        if (instance.isVisible()) {
            instance.setLabelProcessDesc(ProcessDesc);
        }
    }

    private void setLabelProcessDesc(String ProcessDesc){

            jLabelProcessDesc.setText(ProcessDesc);
            if (ProcessDesc.equals("")) {
                jLabelProcessDesc.setVisible(false);
                this.setSize(iFrameWidth, iFrameHeight - iLabelProcessDescHeight);
            } else {
                jLabelProcessDesc.setVisible(true);
                this.setSize(iFrameWidth, iFrameHeight);
            }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSplash = new javax.swing.JLabel();
        jLabelProcessDesc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setUndecorated(true);

        jLabelSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/Splash.jpg"))); // NOI18N
        getContentPane().add(jLabelSplash, java.awt.BorderLayout.CENTER);

        jLabelProcessDesc.setBackground(new java.awt.Color(49, 49, 49));
        jLabelProcessDesc.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelProcessDesc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProcessDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProcessDesc.setOpaque(true);
        jLabelProcessDesc.setPreferredSize(new java.awt.Dimension(56, 30));
        getContentPane().add(jLabelProcessDesc, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void setProcessDesc(String ProcessDesc){
//        jLabelProcessDesc.setText(ProcessDesc);
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSplash3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSplash3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSplash3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSplash3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSplash3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelProcessDesc;
    private javax.swing.JLabel jLabelSplash;
    // End of variables declaration//GEN-END:variables
}
