/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jyms;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author John
 */
public class JFrameSplash extends javax.swing.JFrame {

    private final int iLabelProcessDescHeight;//jLabelProcessDesc
    private final int iFrameHeight;
    private final int iFrameWidth;
    private static JFrameSplash instance = null;
    /**
     * Creates new form JFrameSplash
     */
    public JFrameSplash() {
        initComponents();
        iLabelProcessDescHeight = jLabelProcessDesc.getHeight(); 
        iFrameHeight = this.getHeight();
        iFrameWidth = this.getWidth();
    }
    
    public static void showSplashWindow() {
        if(instance==null){
            instance = new JFrameSplash();
            CommonParas.centerWindow(instance);
            instance.setLabelProcessDesc("");
            instance.setVisible(true);
        }else if (!instance.isVisible()){
            instance.setVisible(true);
        }
    }
    public static void closeSplashWindow(){
        if (instance.isVisible()) 
            instance.dispose();
    }
    
    public static void setProcessDesc(String ProcessDesc){
        //showSplashWindow();
        if (instance.isVisible()) {
            instance.setLabelProcessDesc(ProcessDesc);
        }
    }

    private void setLabelProcessDesc(String ProcessDesc){

            jLabelProcessDesc.setText(ProcessDesc);
            if (ProcessDesc.equals("")) {
                jLabelProcessDesc.setVisible(false);
                //this.setSize(iFrameWidth, iFrameHeight - iLabelProcessDescHeight);
            } else {
                jLabelProcessDesc.setVisible(true);
                //this.setSize(iFrameWidth, iFrameHeight);
            }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel (){

            public void paintComponent(Graphics g)
            {
                int x=0,y=0;
                ImageIcon icon=new ImageIcon(getClass().getResource("/jyms/image/Splash.png"));

                g.drawImage(icon.getImage(),x,y,getSize().width,getSize().height,this);

                while(true){
                    if(x>getSize().width && y>getSize().height)break;
                    //这段代码是为了保证在窗口大于图片时，图片仍能覆盖整个窗口
                    if(x>getSize().width){
                        x=0;
                        y+=icon.getIconHeight();
                    }else
                    x+=icon.getIconWidth();
                }
            }
        };
        jLabelProcessDesc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 488));

        jLabelProcessDesc.setBackground(new java.awt.Color(49, 49, 49));
        jLabelProcessDesc.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelProcessDesc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProcessDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProcessDesc.setPreferredSize(new java.awt.Dimension(56, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelProcessDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 458, Short.MAX_VALUE)
                .addComponent(jLabelProcessDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void setProcessDesc(String ProcessDesc){
//        jLabelProcessDesc.setText(ProcessDesc);
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSplash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelProcessDesc;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
