/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jyms;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jyms.data.ClientLogBean;
import jyms.tools.endecrypt.MD5Encrypt;
import jyms.data.SubUserAuthoritysBean;
import jyms.data.TxtLogger;
import jyms.data.UserAuthoritysBean;
import jyms.data.UsersBean;

/**
 *
 * @author John
 */
public class UserLogin extends javax.swing.JDialog {

    private final String sFileName = this.getClass().getName() + ".java";
    private ArrayList<String> listUserNmes = new ArrayList<>();
    private int iState = 0;//0表示按了“取消”键
    private int iForOpen = 0;//0表示因为是系统登录；1表示是切换用户
    private Jkms jkms;
    private String sDatabaseError = "<html> <p>数据库连接错误！请检查数据库引擎是否启动...</p></html>";
    private String sEnterUserName = "请先输入用户名！";
    private String sEnterPassword = "请先输入密码！";
    private String sUserLogin = "用户登录";
    private String sDataQueryError = "<html> <p>数据查询错误！请与客户服务代表联络...</p></html>";
    private String sUserNotExist = "用户不存在！";
    private String sPasswordError = "密码错误！";
    private String sUnknownError = "<html> <p>出现未知错误！请与客户服务代表联络...</p></html>";
    
    /**
     * Creates new form UserLogin2
     * @param parent
     * @param modal
     * @param ForOpen
     */
    public UserLogin(java.awt.Frame parent, boolean modal, int ForOpen) {
        super(parent, modal);
        try{
            jkms = (Jkms)parent;
            iForOpen = ForOpen;

            initComponents();
            CommonParas.setJButtonUnDecorated(jButtonExit);
            modifyLocales();//国际化
            listUserNmes = UsersBean.getUserNameList(sFileName);
            if (listUserNmes == null){
                jLabelHint.setText(sDatabaseError);//"数据库连接错误！请检查数据库引擎是否启动...";
                return;
            }

            for (int i=0;i<listUserNmes.size();i++){
                jComboBoxUser.addItem(listUserNmes.get(i));
            }
            
        }catch (Exception e){
            TxtLogger.append(sFileName, "jButtonLoginActionPerformed()","系统在登录过程中，出现错误"
                + "\r\n                       Exception:" + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFirst = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jComboBoxUser = new javax.swing.JComboBox<>();
        jLabelPasswrod = new javax.swing.JLabel();
        jPasswordFieldLogin = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelHint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.black);
        setUndecorated(true);

        jPanelFirst.setBackground(new java.awt.Color(64, 64, 64));
        jPanelFirst.setForeground(new java.awt.Color(255, 255, 255));
        jPanelFirst.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogin.setBackground(new java.awt.Color(64, 64, 64));
        jLabelLogin.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/login.png"))); // NOI18N
        jLabelLogin.setText("登 录");
        jPanelFirst.add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 55));

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/close.png"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanelFirst.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 0, 23, 23));

        getContentPane().add(jPanelFirst, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelUserName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUserName.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName.setText("用户名：");

        jComboBoxUser.setEditable(true);
        jComboBoxUser.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jComboBoxUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBoxUserKeyTyped(evt);
            }
        });

        jLabelPasswrod.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPasswrod.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelPasswrod.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPasswrod.setText("密  码：");

        jPasswordFieldLogin.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jPasswordFieldLogin.setToolTipText("");
        jPasswordFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldLoginKeyTyped(evt);
            }
        });

        jButtonLogin.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/ok2.png"))); // NOI18N
        jButtonLogin.setText("登录");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jyms/image/cancel2.png"))); // NOI18N
        jButtonCancel.setText("取消");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelHint.setBackground(new java.awt.Color(0, 0, 0));
        jLabelHint.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelHint.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHint.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabelPasswrod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldLogin)
                            .addComponent(jComboBoxUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(jLabelHint, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName)
                    .addComponent(jComboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasswrod)
                    .addComponent(jPasswordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHint, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxUser, jPasswordFieldLogin});

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:

        String sUserName = jComboBoxUser.getSelectedItem().toString();//jTextFieldUserName.getText().trim();
        String sPassword = new String(jPasswordFieldLogin.getPassword());
        if (sUserName.equals(""))  {
            JOptionPane.showMessageDialog(this, sEnterUserName);//"请先输入用户名！");
            return;
        }else if (sPassword.equals(""))  {
            JOptionPane.showMessageDialog(this, sEnterPassword);//"请先输入密码！");
            return;
        }
        //        PasswordEncrypt passwordEncrypt = new PasswordEncrypt();
        //        sPassword = Integer.toString(passwordEncrypt.toasc(sPassword.charAt(0)));
        try{
            sPassword = MD5Encrypt.getMD5Str(sPassword);

            //        jLabel1.setText(sPassword);
            
            int iIfLogin = UsersBean.UserLogin(sUserName, sPassword,sFileName);
            boolean CheckA = CommonParas.checkAdmin(sUserName, sPassword);
            if (CheckA)  iIfLogin =0;

            switch (iIfLogin) {
                case 0:
                        this.setVisible(false);
                        iState = 1;
                        Date CurrentTime = new Date();
                        String SdfDate = CommonParas.getOperationTime(CurrentTime);//new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(new Date());

                        
                        //如果是第一次登陆而不是切换用户
                        if (CommonParas.UserState.UserName.equals("")){
                        }else{
                            //写日志，注销
                            CommonParas.SystemWriteLog(new ClientLogBean(SdfDate,
                                    CommonParas.UserState.UserName, CommonParas.LogType.LOG_SYS_CODE, CommonParas.sUserLogout), sFileName);
                        }
                        
                        if (CheckA){
                            CommonParas.UserState.UserName = "admin";//设置全局的用户名
                            CommonParas.UserState.LogonTime = CommonParas.SysParas.sysLocales.getOperationTime(CurrentTime);
                            CommonParas.UserState.UserTypeCode = CommonParas.USER_TYPECODE_ADMIN;
                            CommonParas.UserState.UserType = CommonParas.USER_TYPE_ADMIN;
                        }else{
                            //不管切换用户还是第一次登录，都要进行用户全局数据的设置
                            UsersBean usersBean = UsersBean.getUserBean(sUserName, sFileName);
                            CommonParas.UserState.UserName = sUserName;//设置全局的用户名
                            CommonParas.UserState.LogonTime = CommonParas.SysParas.sysLocales.getOperationTime(CurrentTime);
                            CommonParas.UserState.UserTypeCode = usersBean.getUserType();
                            CommonParas.UserState.UserType = CommonParas.getUserType(CommonParas.UserState.UserTypeCode);
                            //系统操作用户的权限
                            if (CommonParas.g_ListUserAuthoritys != null ) CommonParas.g_ListUserAuthoritys.clear();//操作用户的权限

                            CommonParas.g_ListUserAuthoritys = UserAuthoritysBean.getUserAuthoritysList(sUserName,sFileName);
                            if (CommonParas.g_ListSubAuthoritys != null ) CommonParas.g_ListSubAuthoritys.clear();//操作用户的附加权限(设备)
                            CommonParas.g_ListSubAuthoritys = SubUserAuthoritysBean.getSubUserAuthoritysList(sUserName,sFileName);
                        }
                        
                        CommonParas.UserState.setHeadIcon();//设置头像
                        //写日志,用户登录
                        CommonParas.SystemWriteLog(new ClientLogBean(SdfDate, CommonParas.UserState.UserName, CommonParas.LogType.LOG_SYS_CODE, sUserLogin ), sFileName);

                        this.dispose();
                        break;
                case 1:
                        //            jLabel1.setVisible(true);
                        //                jLabel1.setText(CommonParameters.getPasswordGrade(sName,new String(jPasswordFieldLogin.getPassword())));
                        jLabelHint.setText(sDatabaseError);//"数据库连接错误！请检查数据库引擎是否启动...");
                        break;
                case 2:
                        jLabelHint.setText(sDataQueryError );//"数据查询错误！请与客户服务代表联络...");
                        break;
                case 3:
                        jLabelHint.setText(sDataQueryError );//"数据查询错误！请与客户服务代表联络...");
                        break;
                case 4:
                        jLabelHint.setText(sUserNotExist );//"用户不存在！");
                        break;
                case 5:
                        jLabelHint.setText(sPasswordError );//"密码错误！");
                        break;
                default:
                        jLabelHint.setText(sUnknownError );//"出现未知错误！请与客户服务代表联络...");
                        break;
            }
        }catch (Exception e){
            TxtLogger.append(this.sFileName, "jButtonLoginActionPerformed()","系统在登录过程中，出现错误"
                + "\r\n                       Exception:" + e.toString());
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        
//        String sPassword = MD5Encrypt.getMD5Str(new String(jPasswordFieldLogin.getPassword()));
//        System.out.println(sPassword);
        
        iState = 0;
        
        if (iForOpen == 0) { System.exit(0);}
        else this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jPasswordFieldLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldLoginKeyTyped
        // TODO add your handling code here:
        char Code = evt.getKeyChar();
        if (Code == KeyEvent.VK_ENTER){
            jButtonLogin.doClick();
        }
    }//GEN-LAST:event_jPasswordFieldLoginKeyTyped

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        jButtonCancel.doClick();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jComboBoxUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUserKeyTyped

    /**
        * 函数:      modifyLocales
        * 函数描述:  根据系统语言设置窗口的控件信息和消息文本
        * @param Language 设置的系统语言
    */
    private void modifyLocales(){
        
        //if (CommonParas.SysParas.ifChinese) return;//如果是中文，则不做任何操作
        
        MyLocales Locales = CommonParas.SysParas.sysLocales;
        
        //标签和按钮显示
        jLabelLogin.setText(    Locales.getString("ClassStrings", "UserLogin.jLabelLogin"));//登录
        jLabelUserName.setText( Locales.getString("ClassStrings", "UserLogin.jLabelUserName"));//用户名：
        jLabelPasswrod.setText( Locales.getString("ClassStrings", "UserLogin.jLabelPasswrod"));//密码：
        jButtonLogin.setText(   Locales.getString("ClassStrings", "UserLogin.jButtonLogin"));//登录
        jButtonCancel.setText(  Locales.getString("ClassStrings", "UserLogin.jButtonCancel"));//取消
        
        //信息显示
        sDatabaseError          = Locales.getString("MessageStrings", "UserLogin.sDatabaseError");  //数据库连接错误！请检查数据库引擎是否启动...
        sEnterUserName          = Locales.getString("MessageStrings", "UserLogin.sEnterUserName");  //请先输入用户名！
        sEnterPassword          = Locales.getString("MessageStrings", "UserLogin.sEnterPassword");  //请先输入密码！
        sUserLogin              = Locales.getString("MessageStrings", "UserLogin.sUserLogin");  //用户登录
        sDataQueryError         = Locales.getString("MessageStrings", "UserLogin.sDataQueryError");  //数据查询错误！请与客户服务代表联络...
        sUserNotExist           = Locales.getString("MessageStrings", "UserLogin.sUserNotExist");//"用户不存在！"
        sPasswordError          = Locales.getString("MessageStrings", "UserLogin.sPasswordError");  //密码错误！
        sUnknownError           = Locales.getString("MessageStrings", "UserLogin.sUnknownError");  //出现未知错误！请与客户服务代表联络...
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                UserLogin dialog = new UserLogin(new javax.swing.JFrame(), true,0);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JComboBox<String> jComboBoxUser;
    private javax.swing.JLabel jLabelHint;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPasswrod;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFirst;
    private javax.swing.JPasswordField jPasswordFieldLogin;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the iState
     */
    public int getReturnState() {
        return iState;
    }

}
